artifact_location: file:///Users/alexandersoldatkin/projects/cos_rewrite_mlflow/mlruns_test/0
creation_time: 1768075478758
experiment_id: '0'
last_update_time: 1768075478758
lifecycle_stage: active
name: Default
