from datetime import datetime
from typing import Optional, List, Any, Dict
from pydantic import BaseModel, Field

class RollingWindowNodeFeatures(BaseModel):
    """
    Represents features for a single node within a specific rolling window period.
    Generated by the rolling window pipeline (GraphSAGE/FastRP + Centrality).
    """
    
    # Node Identifiers
    node_id: int = Field(..., alias="nodeId", description="Internal Neo4j ID at the time of export.")
    entity_id: Optional[str] = Field(None, description="Stable entity identifier (e.g. hash of attributes).")
    id: Optional[str] = Field(None, alias="Id", description="Original ID (e.g. INN or UUID).")
    node_labels: Optional[List[str]] = Field(None, alias="nodeLabels", description="List of node labels.")
    
    # Window Metadata
    window_start_ms: Optional[int] = Field(None, description="Window start timestamp (ms).")
    window_end_ms: Optional[int] = Field(None, description="Window end timestamp (ms).")
    window_start_year: Optional[int] = Field(None, description="Start year of the window.")
    window_end_year_inclusive: Optional[int] = Field(None, description="End year of the window (inclusive).")
    window_graph_name: Optional[str] = Field(None, description="Name of the projected graph in Neo4j GDS.")
    params_hash: Optional[str] = Field(None, description="Hash of the configuration parameters used.")

    # Graph Topology    # Network Metrics
    degree: Optional[float] = Field(None, description="Total Degree.")
    in_degree: Optional[float] = Field(None, description="In-Degree.")
    out_degree: Optional[float] = Field(None, description="Out-Degree.")
    page_rank: Optional[float] = Field(None, description="PageRank score.")
    betweenness: Optional[float] = Field(None, description="Betweenness Centrality score.")
    closeness: Optional[float] = Field(None, description="Closeness Centrality score.")
    eigenvector: Optional[float] = Field(None, description="Eigenvector Centrality score.")
    wcc: Optional[float] = Field(None, description="Weakly Connected Components ID.")
    community_louvain: Optional[float] = Field(None, description="Louvain Community ID.")
    
    # Target / Labels
    is_dead: Optional[bool] = Field(None, description="Target label: True if the bank failed in the prediction horizon.")

    # Feature Vectors (Embeddings & Aggregations)
    fastrp_embedding: Optional[List[float]] = Field(None, description="FastRP embedding vector.")
    
    # Domain-Specific Feature Vectors
    bank_feats: Optional[List[float]] = Field(None, description="Banking indicator features (from Report 101/102).")
    state_feats: Optional[List[float]] = Field(None, description="State ownership/relation features.")
    legal_feats: Optional[List[float]] = Field(None, description="Legal structure features.")
    governance_feats: Optional[List[float]] = Field(None, description="Governance/Management features.")
    finance_feats: Optional[List[float]] = Field(None, description="General financial features.")
    ip_feats: Optional[List[float]] = Field(None, description="Intellectual Property features.")
    ops_feats: Optional[List[float]] = Field(None, description="Operational features.")
    other_feats: Optional[List[float]] = Field(None, description="Other miscellaneous features.")

    # Combined Network Features (often a concatenation or processed version)
    network_feats: Optional[List[float]] = Field(None, description="Combined network features.")

    model_config = {
        "populate_by_name": True,
        "arbitrary_types_allowed": True
    }
